# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/cask-drivers"
tap "homebrew/services"
tap "devopsdays/tap"
tap "heroku/brew"
tap "sass/sass"
tap "teamookla/speedtest"
tap "romkatv/powerlevel10k"

# Brew CLI apps
brew "asciinema"
brew "aom"
brew "autojump"
brew "awscli"
brew "azure-cli"
brew "diff-so-fancy"
brew "direnv"
brew "ffmpeg"
brew "gh"
brew "ghostscript"
brew "git-extras"
brew "gnupg"
brew "go"
brew "graphicsmagick"
brew "helm"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "jpeg-xl"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "neovim"
brew "node"
brew "netlify-cli", link: false
brew "openjpeg"
brew "openssh"
brew "perl"
brew "ponysay"
brew "postgresql"
brew "powerlevel10k"
brew "pulumi"
brew "qrencode"
brew "sass/sass/sass"
brew "speedtest"
brew "thefuck"
brew "tldr"
brew "tree"
brew "vim"
brew "wget"
brew "webp"
brew "yadm"
brew "yarn"
brew "yt-dlp" #replaces youtube-dl
#brew "youtube-dl"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "devopsdays/tap/devopsdays-cli"
brew "heroku/brew/heroku"


# App casks
cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "aerial"
cask "asana"
cask "alfred"
cask "audio-hijack"
cask "bartender"
cask "beyond-compare"
cask "dash"
cask "discord"
cask "docker"
# cask "elgato-game-capture-hd"
# OBS must be installed before Stream Deck
cask "obs"
cask "elgato-stream-deck"
cask "grammarly"
cask "google-chrome"
cask "iterm2"
cask "logitech-presentation"
cask "loopback"
cask "macdown"
cask "microsoft-office"
cask "microsoft-teams"
cask "moom"
cask "ngrok"
cask "obs"
cask "obsidian"
cask "postman"
cask "signal"
cask "slack"
cask "soundsource"
cask "tower"
cask "visual-studio-code"
cask "zoom"

# Font casks
cask "font-hack-nerd-font"
cask "font-inconsolata-for-powerline"
cask "font-menlo-for-powerline"
