# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/cask-drivers"
tap "homebrew/services"
tap "devopsdays/tap"
tap "heroku/brew"
tap "teamookla/speedtest"
tap "romkatv/powerlevel10k"

# Brew CLI apps
brew "1password-cli"
brew "asciinema"
brew "autojump"
brew "awscli"
brew "azure-cli"
brew "diff-so-fancy"
brew "direnv"
brew "gh"
brew "git-extras"
brew "gnupg"
brew "go"
brew "graphicsmagick"
brew "helm"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "neovim"
brew "node"
brew "netlify-cli", link: false
brew "packer"
brew "ponysay"
brew "pulumi"
brew "qrencode"
brew "speedtest"
brew "thefuck"
brew "tldr"
brew "tree"
brew "vim"
brew "wget"
brew "yadm"
brew "yarn"
brew "youtube-dl"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "devopsdays/tap/devopsdays-cli"
brew "heroku/brew/heroku"
brew "romkatv/powerlevel10k/powerlevel10k"

# App casks
cask "1password"
cask "adobe-creative-cloud"
cask "aerial"
cask "airfoil"
cask "airtable"
cask "asana"
cask "audio-hijack"
cask "authy"
cask "alfred"
cask "bartender"
cask "beyond-compare"
cask "cron"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "elgato-control-center"
cask "fantastical"
# cask "elgato-game-capture-hd"
# OBS must be installed before Stream Deck
cask "obs"
cask "elgato-stream-deck"
cask "farrago"
cask "firefox"
cask "fission"
cask "grammarly"
cask "google-chrome"
cask "handbrake"
cask "iterm2"
cask "loopback"
cask "keybase"
cask "logitech-presentation"
cask "macdown"
cask "microsoft-office"
cask "microsoft-teams"
cask "moom"
cask "ngrok"
cask "notion"
cask "postman"
cask "remarkable"
cask "signal"
cask "skype"
cask "slack"
cask "soundsource"
cask "spotify"
cask "steam"
cask "tower"
cask "visual-studio-code"
cask "zoom"

# Font casks
cask "font-hack-nerd-font"
cask "font-inconsolata-for-powerline"
cask "font-menlo-for-powerline"

# Mac App Store apps
mas "DaisyDisk", id: 411643860
mas "HP Smart for Desktop", id: 1474276998
mas "iMovie", id: 408981434
mas "Just Press Record", id: 979561272
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Microsoft Remote Desktop", id: 1295203466
mas "MindNode", id: 1289197285
mas "ToothFairy", id: 1191449274
mas "Webcam Settings", id: 533696630
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
